image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  script:
    - docker build --target test .

build:
  stage: build
  before_script:
    - export FQIN=$FQIP:$(git describe --always --tags)
  script:
    - docker build --target build -t $FQIN .