stages:
  - build
  - publish

before_script:
  - export FQIN=$FQIP:$(git describe --always --tags)

build:
  environment: dev
  stage: build
  script:
    - docker build --target publish -t $FQIN .

publish:
  environment: dev
  stage: publish
  script:
    - docker run -e UV_PUBLISH_URL -e UV_PUBLISH_TOKEN "$FQIN"
