stages:
  - build
  - publish

before_script:
  - export FQIN=$FQIP:$(git describe --always --tags)

build:
  environment: production
  stage: build
  only:
    - tags
  script:
    - docker build --target publish -t $FQIN .

publish:
  environment: production
  stage: publish
  only:
    - tags
  script:
    - docker run -e UV_PUBLISH_TOKEN "$FQIN"
