stages:
  - build
  - publish

before_script:
  - export FQIN=$FQIP:$(git describe --always --tags)

build:
  environment: dev
  stage: build
  script:
    - docker build --target build -t $FQIN .

publish:
  environment: dev
  stage: publish
  script:
    - docker run "$FQIN"
